### ISSUE TITLE
Bug in linear enslavement

### ISSUE THREAD

**Issue by ndeconto** [TelecomParistoc/MotorController#17]
When I try to debug PID_Learning, calls to the function move (in libmotors) are done. However, the (big) robot doesn't move at all. It seems that the problem comes from MotorController. 

## How to reproduce the bug

First, I started on the big robot the test in PID_Learning, and I got the following logs. 
```
pi@illuminapi:~/PID_Learning/test $ build/test_simulated_move 
[Info] Starting a new experiment with multiplicative coeff for temperature : 0.993116 => giving coeff^n_iterations = 0.001
[Info] Testing PID (700, 0, 0)
Calling move(200)
calling callback 0x1f128...
Calling turn(357)
Calling move(-190)
```

Then, the program waits endlessly for the callback... 

## Debug information

According to the following logs, it seems the STM32 got the right order.

```
rx_buffer = 0xA0 66 255
rx_buffer = 0xA2 255 255
cur_pos = (1190, 991)
target 5712 / 5712 (5723) -6 / -190 (0)
cur_pos = (1190, 991)
target 5712 / 5712 (5723) -93 / -190 (0)
cur_pos = (1190, 991)
target 5712 / 5712 (5723) -182 / -190 (0)
cur_pos = (1190, 991)
target 5712 / 5712 (5723) -190 / -190 (0)
cur_pos = (1190, 991)
target 5712 / 5712 (5723) -190 / -190 (0)
cur_pos = (1190, 991)
```

This is the log which corresponds to:
```C
printf("cur_pos = (%.3f, %.3f)\n", (float) cur_pos.x, cur_pos.y);
printf("target %d / %d (%d) %d / %d (%d)\r\n", target_heading, goal.heading, orientation, target_dist, goal.mean_dist, current_distance);
```

Remainder: MotorController/inc/i2c_interface_addr.h: lines 100 to 105

```C
// goal mean distance (in mm)
#define GOAL_MEAN_DIST_LOW_ADDR 0xa0U
#define GOAL_MEAN_DIST_HIGH_ADDR 0xa2U

// goal heading (in °)
#define GOAL_HEADING_ADDR 0xa4U
```

## Remarks
It seems linear enslavement is disabled. Indeed, when I push the (big) robot with a translation, it does not react. But when I try to turn it, enslavement works well.  (Motor power is on!)

**Comment by le-roux** [comment]
Which version of the code do you use?

**Comment by ndeconto** [comment]
The last version on “master”

De : le-roux<mailto:notifications@github.com>
Envoyé : ‎vendredi‎ ‎16‎ ‎février‎ ‎2018 ‎20‎:‎16
À : TelecomParistoc/MotorController<mailto:MotorController@noreply.github.com>
Cc : ndeconto<mailto:nicodeconto@hotmail.fr>, Assign<mailto:assign@noreply.github.com>


Which version of the code do you use?

**Comment by le-roux** [comment]
It's because the PID coeffs are set to 0.
