### ISSUE TITLE
Makefile : variable $PROJECT = SwARM

### ISSUE THREAD

**Issue by ndeconto** [TelecomParistoc/MotorController#7]
line 86 : PROJECT = SwARM ...

**Comment by le-roux** [comment]
Comme c'est le même microcontrôleur que Swarm, j'ai récupéré leur portage de ChibiOs, mais effectivement je n'ai pas modifié le nom.
Je l'inclurai dans le prochain commit.

**Comment by le-roux** [comment]
Closed by commit b88f282
